#
# Travis-CI configuration for dt-init.
#

sudo: false
language: node_js
node_js:
    - "0.10"
    - 0.11

# Install TypeScript compiler to compile definitions and test files.
# Install bower which is used to retrieve client-side dependencies.
# Build dt-init from TypeScript source first (but this uses gulp-typescript).
before_script: npm install -g typescript bower && npm run build
script: ./test-mocha # Invoke mocha tests for dt-init.
