#!/usr/bin/env node
var exec = require('child_process').exec;
console.log('Building dt-init...');
exec('gulp', function(){});
exec('chmod +x dt-init', function(){});;
exec('npm pack', function(){});

