#!/usr/bin/env node
/*
dt-init
Utility to generate TypeScript definitions and test stubs.
Copyright 2015 Sam Saint-Pettersen.

Released under the MIT License.
*/
var DTInit = require('./dt-init-lib');
new DTInit(process.argv[2]);
